name: CI Pipeline

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify package.json exists
        run: test -f package.json || (echo "package.json not found!" && exit 1)

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        env:
          CI: true

      - name: Verify node_modules directory exists
        run: test -d node_modules || (echo "node_modules directory not found!" && exit 1)

      - name: Build and Test
        run: |
          npm run build
          npm test
